### ISSUE TITLE
malilib error

### ISSUE THREAD

**Issue by BDXA** [maruohon/minihud#227]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install malilib, version 0.10.0-dev.26 or later.
Unmet dependency listing:
	 - Mod 'MiniHUD' (minihud) 0.20.0-dev.20211204.182009 requires version 0.10.0-dev.26 or later of malilib, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by vacla** [comment]
@BDXA you need to install malilib

**Comment by BDXA** [comment]
yeah i think im retarded

**Comment by BDXA** [comment]
its working now
