### ISSUE TITLE
Large Box Shape Out of Memory Error

### ISSUE THREAD

**Issue by B34rd0** [maruohon/minihud#235]
I tried creating a large 1y layer box so I knew what level to dig down to, but once I put the second Z range in (about 300 apart) my game crashed with an 'out of memory' error. Now I can no longer enter my save with Minihud enabled. Is there a way to delete the shape from a config file so I can use my world again with Minihud enabled?

Error Log:

java.lang.OutOfMemoryError: Failed to resize buffer from 2145386496 bytes to -2147483648 bytes
	at net.minecraft.class_311.method_37465(class_311.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.method_1335(class_287.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.method_22892(class_287.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.method_1344(class_287.java:440) ~[client-intermediary.jar:?]
	at fi.dy.masa.minihud.renderer.shapes.ShapeBox.renderGridLinesY(ShapeBox.java:238) ~[minihud-fabric-1.18.2-0.22.0.jar:?]
	at fi.dy.masa.minihud.renderer.shapes.ShapeBox.renderGridLines(ShapeBox.java:167) ~[minihud-fabric-1.18.2-0.22.0.jar:?]
	at fi.dy.masa.minihud.renderer.shapes.ShapeBox.renderBox(ShapeBox.java:159) ~[minihud-fabric-1.18.2-0.22.0.jar:?]
	at fi.dy.masa.minihud.renderer.shapes.ShapeBox.update(ShapeBox.java:133) ~[minihud-fabric-1.18.2-0.22.0.jar:?]
	at fi.dy.masa.minihud.renderer.RenderContainer.update(RenderContainer.java:85) ~[minihud-fabric-1.18.2-0.22.0.jar:?]
	at fi.dy.masa.minihud.renderer.RenderContainer.render(RenderContainer.java:65) ~[minihud-fabric-1.18.2-0.22.0.jar:?]
	at fi.dy.masa.minihud.renderer.OverlayRenderer.renderOverlays(OverlayRenderer.java:63) ~[minihud-fabric-1.18.2-0.22.0.jar:?]
	at fi.dy.masa.minihud.event.RenderHandler.onRenderWorldLast(RenderHandler.java:178) ~[minihud-fabric-1.18.2-0.22.0.jar:?]
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:111) ~[malilib-fabric-1.18.2-0.12.1.jar:?]
	at net.minecraft.class_761.handler$ben000$onRenderWorldLastNormal(class_761.java:6404) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:2222) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1542) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:1158) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18:38:27] [Render thread/INFO]: Stopping!
[18:38:27] [CullThread/INFO]: [STDOUT]: Shutting down culling task!
Process exited with code 0.
MultiMC: Log upload triggered at: 04 May 2022 18:42:14 +0100

**Comment by maruohon** [comment]
I need to add safe guard to the box coordinates...

You can edit the config file and fix the shape or just delete it at `.minecraft/config/minihud/worldorservername_dimension.json`

**Comment by B34rd0** [comment]
> I need to add safe guard to the box coordinates...
> 
> You can edit the config file and fix the shape or just delete it at `.minecraft/config/minihud/worldorservername_dimension.json`

Thank you kindly. Should I close the issue?

**Comment by B34rd0** [comment]
It actually wasn't because I made the box too big, it was caused by me deleting out the value and leaving '.xxxxxxx' as a value before inputting a new value I don't know if this is helpful.

**Comment by maruohon** [comment]
I think the size just got too large due to derpy coordinate change order, and I don't think it has any kind of clamping for a maximum size atm.

I added it to my todo list text file, so I'll close this.
