### ISSUE TITLE
Minecraft crashing on launch

### ISSUE THREAD

**Issue by uddipmayur** [maruohon/minihud#254]
When adding the latest version of minihud and malilib on fabric, the game crashes every time and shows the erroe of incompatible mod
![Uploading 16595304260374094516814634084971.jpg…]()

**Comment by kosma** [comment]
The image in your bug report is broken, care to reupload?

**Comment by Pro-grammer3764** [comment]
I have the same issue, here is the copied error message from fabric mod loader:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Litematica' (litematica) 0.12.3 with any version that is compatible with:
		 - minecraft 1.19
	 - Replace mod 'MiniHUD' (minihud) 0.23.1 with any version that is compatible with:
		 - minecraft 1.19
Unmet dependency listing:
	 - Mod 'Litematica' (litematica) 0.12.3 requires any version between 1.19.1 (inclusive) and 1.20 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	 - Mod 'Litematica' (litematica) 0.12.3 requires any 0.13.x version of malilib, which is missing!
	 - Mod 'MiniHUD' (minihud) 0.23.1 requires any version between 1.19.1 (inclusive) and 1.20 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	 - Mod 'MiniHUD' (minihud) 0.23.1 requires any 0.13.x version of malilib, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by vacla** [comment]
@Pro-grammer3764 you are using the 1.19.1 versions for 1.19, you need to download the 1.19 versions of the mods and you also need malilib

**Comment by maruohon** [comment]
No info provided, and the issue was most likely just using the wrong mod versions, closing.
