### ISSUE TITLE
[Fabric 1.19] Crash when sending a chat message with only a space

### ISSUE THREAD

**Issue by HeyBanditoz** [maruohon/minihud#255]
I would guess the problem lies [here](https://github.com/maruohon/minihud/blob/abbce6c0156e534366e1a4ffeb31def997c350b6/src/main/java/fi/dy/masa/minihud/util/DataStorage.java#L359-L361) `args[0]` is OOB for a string with only spaces so it crashes out.
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at fi.dy.masa.minihud.util.DataStorage.onSendChatMessage(DataStorage.java:361)
	at net.minecraft.client.gui.screen.ChatScreen.handler$bic000$onSendChatMessage(ChatScreen:1102)
	at net.minecraft.client.gui.screen.ChatScreen.method_44056(ChatScreen)
	at net.minecraft.client.gui.screen.ChatScreen.keyPressed(ChatScreen:213)
	at net.minecraft.client.Keyboard.method_1454(Keyboard:374)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:489)
	at net.minecraft.client.Keyboard.onKey(Keyboard:370)
	at net.minecraft.client.Keyboard.method_22678(Keyboard:462)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103)
	at net.minecraft.client.Keyboard.method_22676(Keyboard:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:197)
	at net.minecraft.client.util.Window.swapBuffers(Window:315)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1204)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:767)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)

```

**Comment by fooeyround** [comment]
#256 should fix this?
