### ISSUE TITLE
NullPointerException when enabling "spawn chunk real" renderer

### ISSUE THREAD

**Issue by cfandrews** [maruohon/minihud#277]
Crash report:

```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2022-10-11 10:41:39
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_27383" because "this.field_27368" is null
	at net.minecraft.class_291.method_35665(class_291.java:107)
	at net.minecraft.class_291.method_34431(class_291.java:176)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at fi.dy.masa.minihud.renderer.RenderObjectVbo.draw(RenderObjectVbo.java:60)
	at fi.dy.masa.minihud.renderer.OverlayRendererBase.draw(OverlayRendererBase.java:82)
	at fi.dy.masa.minihud.renderer.RenderContainer.draw(RenderContainer.java:123)
	at fi.dy.masa.minihud.renderer.RenderContainer.render(RenderContainer.java:66)
	at fi.dy.masa.minihud.renderer.OverlayRenderer.renderOverlays(OverlayRenderer.java:63)
	at fi.dy.masa.minihud.event.RenderHandler.onRenderWorldLast(RenderHandler.java:178)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:111)
	at net.minecraft.class_761.handler$bag000$onRenderWorldLastFabulous(class_761.java:4990)
	at net.minecraft.class_761.method_22710(class_761.java:1533)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_291.method_35665(class_291.java:107)
	at net.minecraft.class_291.method_34431(class_291.java:176)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at fi.dy.masa.minihud.renderer.RenderObjectVbo.draw(RenderObjectVbo.java:60)
	at fi.dy.masa.minihud.renderer.OverlayRendererBase.draw(OverlayRendererBase.java:82)
	at fi.dy.masa.minihud.renderer.RenderContainer.draw(RenderContainer.java:123)
	at fi.dy.masa.minihud.renderer.RenderContainer.render(RenderContainer.java:66)
	at fi.dy.masa.minihud.renderer.OverlayRenderer.renderOverlays(OverlayRenderer.java:63)
	at fi.dy.masa.minihud.event.RenderHandler.onRenderWorldLast(RenderHandler.java:178)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:111)
	at net.minecraft.class_761.handler$bag000$onRenderWorldLastFabulous(class_761.java:4990)
	at net.minecraft.class_761.method_22710(class_761.java:1533)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Affected level --
Details:
	All players: 1 total; [class_746['username redacted'/2699, l='ClientLevel', x=-13.77, y=72.00, z=-206.80]]
	Chunk stats: 16384, 3653
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,68,-144), Section: (at 0,4,0 in -2,4,-9; chunk contains blocks -32,-64,-144 to -17,319,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 2543258 game time, 3074803 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 3
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks_r434183.zip

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (aarch64) version 12.5
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 489370016 bytes (466 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 10
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1 Max
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 10
	Graphics card #0 name: Apple M1 Max
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 32768.00
	Virtual memory used (MB): 17829.67
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M1 Max GL version 4.1 Metal - 76.3, Apple
	Window size: 3024x1890
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fabulous
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks_r434183.zip
	Current Language: English (US)
	CPU: 10x Apple M1 Max
	Server Running: true
	Player Count: 1 / 8; [class_3222['username redacted'/2699, l='ServerLevel[Survival]', x=-13.77, y=72.00, z=-206.80]]
	Data Packs: vanilla
	World Generation: Stable
```

**Comment by cfandrews** [comment]
Looks like [someone else](https://github.com/maruohon/minihud/issues/270) experienced this not too long ago, I'd probably at least wrap whatever is causing the issue in a try-catch block and either throw a custom exception with more info or reset the spawn chunk renderer to be not enabled if possible.

I'm not familiar with this code base at all though and couldn't figure out where the actual error occurred in it, if it's an issue with your code and not with Minecraft itself then it might be fixable otherwise I would go for the try-catch block solution

**Comment by maruohon** [comment]
That NPE is from vanilla code, from a place where it should not be possible. If it's not a cross-mod issue of some kind, then my only/best guess atm is that the game would be running out of video memory. No idea how else it could happen. And it should be the same code that is used for all overlays.

Unless it's some weird issue where if an overlay is being rendered when you are very far from its location, then something funky happens. (That is apparently an issue for example with the sphere shapes, where them being very far away and/or in certain angle from the player, will cause massive fps issues, via some vanilla framebuffer flip code or whatever it was, which I think means it happens somewhere deep in the graphics pipeline?)

**Comment by Disorientedkenny** [comment]
Tried to use the line renderer, accidentally clicked "set here" for the max, and had 0.5,0.5,0.5 for the min. Instantly crashed my game and now I can't load the server with Minihud in the mods folder. Replacing the minihud jar did nothing. How can I resolve this so I can keep using Minihud @maruohon

**Comment by Disorientedkenny** [comment]
> Tried to use the line renderer, accidentally clicked "set here" for the max, and had 0.5,0.5,0.5 for the min. Instantly crashed my game and now I can't load the server with Minihud in the mods folder. Replacing the minihud jar did nothing. How can I resolve this so I can keep using Minihud @maruohon

deleted config for minihud, works now
