### ISSUE TITLE
Crash when enabling pathfinding

### ISSUE THREAD

**Issue by litoj** [maruohon/minihud#287]
```
java.lang.ArrayIndexOutOfBoundsException: Index 122 out of bounds for length 26
	at net.minecraft.class_2540.method_10818(class_2540.java:478)
	at net.minecraft.class_9.method_47935(class_9.java:155)
	at net.minecraft.class_9.method_28(class_9.java:147)
	at net.minecraft.class_11.method_34(class_11.java:211)
	at fi.dy.masa.minihud.util.DebugInfoUtils.onServerTickEnd(DebugInfoUtils.java:188)
	at net.minecraft.server.MinecraftServer.handler$cfc000$onServerTickPost(MinecraftServer.java:4788)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:868)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ChickenNdWaffles** [comment]
I also experience a crash when I toggle pathfinding ever since the most recent update.
