### ISSUE TITLE
Crash when enabling Pathfinding

### ISSUE THREAD

**Issue by GravityCY** [maruohon/minihud#298]
```java
java.lang.ArrayIndexOutOfBoundsException: Index 115 out of bounds for length 26
	at net.minecraft.class_2540.method_10818(class_2540.java:478)
	at net.minecraft.class_9.method_47935(class_9.java:155)
	at net.minecraft.class_9.method_28(class_9.java:147)
	at net.minecraft.class_11.method_34(class_11.java:211)
	at fi.dy.masa.minihud.util.DebugInfoUtils.onServerTickEnd(DebugInfoUtils.java:188)
	at net.minecraft.server.MinecraftServer.handler$ccm000$minihud$onServerTickPost(MinecraftServer.java:5288)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:868)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ChickenNdWaffles** [comment]
I have the same issue. Have since like... 1.19.3 I think. Somewhere around then. It sucks, I used toggle pathfinding very often.

**Comment by BR184** [comment]
same in 1.20.1

**Comment by carljohnson93** [comment]
Same issue guys

**Comment by Culacc1no01** [comment]
same in 1.20.1 too
