### ISSUE TITLE
Crash on trying to render a too large "line (blocks)"

### ISSUE THREAD

**Issue by SterniXP** [maruohon/minihud#316]
Edit: crash was caused by too large object apparently,
 -6000 to 6000 (missed a minus there)
a warning would be nice if possible

other than that great mod :)

Stacktrace:
java.lang.NullPointerException: Cannot read field "field_27383" because "this.field_27368" is null
	at net.minecraft.class_291.method_35665(class_291.java:109)
	at net.minecraft.class_291.method_34431(class_291.java:181)
	at net.minecraft.class_291.method_34427(class_291.java:123)
	at fi.dy.masa.minihud.renderer.RenderObjectVbo.draw(RenderObjectVbo.java:55)
	at fi.dy.masa.minihud.renderer.shapes.ShapeBlocky.draw(ShapeBlocky.java:98)
	at fi.dy.masa.minihud.renderer.RenderContainer.draw(RenderContainer.java:122)
	at fi.dy.masa.minihud.renderer.RenderContainer.render(RenderContainer.java:66)
	at fi.dy.masa.minihud.renderer.OverlayRenderer.renderOverlays(OverlayRenderer.java:63)
	at fi.dy.masa.minihud.event.RenderHandler.onRenderWorldLast(RenderHandler.java:176)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:114)
	at net.minecraft.class_761.handler$dco000$malilib$onRenderWorldLastNormal(class_761.java:10948)
	at net.minecraft.class_761.method_22710(class_761.java:1544)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	

Mixins in Stacktrace:
	net.minecraft.class_291:
		net.coderbot.iris.mixin.MixinVertexBuffer (mixins.iris.json)
	net.minecraft.class_761:
		fi.dy.masa.malilib.mixin.MixinWorldRenderer (mixins.malilib.json)
		fi.dy.masa.litematica.mixin.MixinWorldRenderer (mixins.litematica.json)
		net.coderbot.batchedentityrendering.mixin.MixinLevelRenderer_EntityListSorting (iris-batched-entity-rendering.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.options.weather.WorldRendererMixin (sodium.mixins.json)
		carpet.mixins.LevelRenderer_scarpetRenderMixin (carpet.mixins.json)
		net.fabricmc.fabric.mixin.client.rendering.WorldRendererMixin (fabric-rendering-v1.mixins.json)
		net.fabricmc.fabric.mixin.resource.loader.client.KeyedResourceReloadListenerClientMixin (fabric-resource-loader-v0.client.mixins.json)
		carpet.mixins.LevelRenderer_pausedShakeMixin (carpet.mixins.json)
		net.coderbot.iris.mixin.fantastic.MixinLevelRenderer (mixins.iris.fantastic.json)
		me.jellysquid.mods.sodium.mixin.features.render.world.clouds.WorldRendererMixin (sodium.mixins.json)
		net.coderbot.iris.mixin.MixinLevelRenderer (mixins.iris.json)
		me.jellysquid.mods.sodium.mixin.core.render.world.WorldRendererMixin (sodium.mixins.json)
		net.coderbot.iris.mixin.LevelRendererAccessor (mixins.iris.json)
		net.coderbot.iris.mixin.vertices.immediate.MixinLevelRenderer (mixins.iris.vertexformat.json)
		fi.dy.masa.tweakeroo.mixin.MixinWorldRenderer (mixins.tweakeroo.json)
		me.jellysquid.mods.sodium.mixin.features.render.gui.outlines.WorldRendererMixin (sodium.mixins.json)
		carpet.mixins.LevelRenderer_fogOffMixin (carpet.mixins.json)
		net.coderbot.batchedentityrendering.mixin.MixinLevelRenderer (iris-batched-entity-rendering.mixins.json)
		net.coderbot.iris.compat.sodium.mixin.sky.MixinLevelRenderer (mixins.iris.compat.sodium.json)
		carpet.mixins.LevelRenderer_creativeNoClipMixin (carpet.mixins.json)
		net.coderbot.iris.mixin.shadows.MixinLevelRenderer (mixins.iris.json)
		net.coderbot.iris.mixin.shadows.MixinPreventRebuildNearInShadowPass (mixins.iris.json)
		net.coderbot.iris.mixin.fabulous.MixinDisableFabulousGraphics (mixins.iris.json)
		net.coderbot.iris.mixin.sky.MixinLevelRenderer_SunMoonToggle (mixins.iris.json)
		fi.dy.masa.minihud.mixin.IMixinWorldRenderer (mixins.minihud.json)
	net.minecraft.class_757:
		nl.enjarai.doabarrelroll.mixin.client.roll.GameRendererMixin (do-a-barrel-roll.client.mixins.json)
		net.coderbot.iris.mixin.MixinGameRenderer_NightVisionCompat (mixins.iris.json)
		net.coderbot.iris.mixin.MixinTweakFarPlane (mixins.iris.json)
		net.fabricmc.fabric.mixin.client.rendering.shader.GameRendererMixin (fabric-rendering-v1.mixins.json)
		net.fabricmc.fabric.mixin.screen.GameRendererMixin (fabric-screen-api-v1.mixins.json)
		net.coderbot.iris.mixin.GameRendererAccessor (mixins.iris.json)
		org.anti_ad.mc.ipnext.mixin.MixinGameRenderer (mixins.ipnext.json)
		xaero.common.mixin.MixinGameRenderer (xaerominimap.mixins.json)
		xaero.map.mixin.MixinGameRenderer (xaeroworldmap.mixins.json)
		fuzs.puzzleslib.mixin.client.GameRendererFabricMixin (puzzleslib.fabric.mixins.json)
		fi.dy.masa.tweakeroo.mixin.MixinGameRenderer (mixins.tweakeroo.json)
		net.coderbot.iris.mixin.MixinModelViewBobbing (mixins.iris.json)
		net.coderbot.iris.mixin.MixinGameRenderer (mixins.iris.json)
		me.jellysquid.mods.sodium.mixin.features.gui.hooks.console.GameRendererMixin (sodium.mixins.json)
		
JVM Flags: 
9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		appleskin: AppleSkin 2.5.0+mc1.20
		carpet: Carpet Mod 1.4.112+v230608
		carpet-tis-addition: Carpet TIS Addition 1.50.1
			conditional-mixin: conditional mixin 0.3.2
		cleardespawn: Clear Despawn 1.1.13
		clickthrough: ClickThrough 1.20-fabric0.83.0-0.4.1
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.4+1.20
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.3+1.20.1
		do_a_barrel_roll: Do a Barrel Roll 3.2.0+1.20
			cicada: CICADA 0.4.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		durabilityviewer: Giselbaers Durability Viewer 1.20-fabric0.83.0-1.10.5
			cardinal-components-base: Cardinal Components API (base) 5.2.0
			cardinal-components-entity: Cardinal Components API (entities) 5.2.0
		enchantedtooltips: Enchanted ToolTips 1.3.7-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		forgeconfigapiport: Forge Config API Port 8.0.0
		fps: FPS Monitor 1.20-1.3.0-Fabric
		held-item-info: Held Item Info 1.5.0
		indium: Indium 1.0.25+mc1.20.1
		inventoryprofilesnext: Inventory Profiles Next 1.10.7
		iris: Iris 1.6.8
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		libipn: libIPN 4.0.0
		litematica: Litematica 0.15.0
		malilib: MaLiLib 0.16.0
		maptooltip: Map Tooltip 3.0.0
		minecraft: Minecraft 1.20.1
		minihud: MiniHUD 0.27.0
		mixintrace: MixinTrace 1.1.1+1.17
		mobplaques: Mob Plaques 8.0.0
		modmenu: Mod Menu 7.2.1
		mousetweaks: Mouse Tweaks 2.25
		puzzleslib: Puzzles Lib 8.0.13
		sodium: Sodium 0.5.2
		sprintindicator: Sprint Indicator 1.2.0
		tweakeroo: Tweakeroo 0.17.0
		voicechat: Simple Voice Chat 1.20.1-2.4.21
		xaerominimap: Xaero's Minimap 23.6.2
		xaeroworldmap: Xaero's World Map 1.33.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
	Loaded Shaderpack: (off)

**Comment by maruohon** [comment]
Yeah unfortunately the line shape is still missing the check/limit for preventing too large shapes. However I'm skeptical about that being the cause for the crash in this log, usually that would crash with some form of OutOfMemory error.

I've seen this crash (same/similar stack trace) a number of times recently, and I'm more thinking it might be some kind of GPU driver related issue, or maybe related to some other mod doing something. In any case it's because some of the stuff in the renderer was not initialized like it normally should. And unfortunately I don't have a check for this stuff not being null currently... Probably should add it to prevent crashes. But on the other hand then there might be mysterious issues of things just not rendering without explanation. Probably would need to then also print a warning and maybe disable the renderer automatically.
