### ISSUE TITLE
[BUG]打开寻路导致游戏崩溃,Pathfinding

### ISSUE THREAD

**Issue by 100210110** [maruohon/minihud#322]
Minecraft Version
1.19.4

Version
MasaGadget-1.19.4-3.2.311+aae0554-stable
minihud-fabric-1.19.4-0.26.2

Description
image
这个minihud的功能开启后会导致游戏崩溃，崩溃后启动器弹出可能是minihud和masagadget导致
image

To Reproduce
打开游戏，使用minihud-fabric-1.19.4-0.26.2和MasaGadget-1.19.4-3.2.311+aae0554-stable
进入游戏，进入单人世界，打开minihud的Pathfinding，然后，游戏就结束了自己
我刚刚把mod升级到最新，MasaGadget-1.19.4-3.2.318+67ab5b4-stable
这个崩溃仍然存在也依然提示minihud和gadget导致崩溃

Expected behavior
我希望打开功能后，游戏不崩溃，正常渲染村民寻路
[错误报告-2023-9-10_14.25.36.zip](https://github.com/maruohon/minihud/files/12567677/-2023-9-10_14.25.36.zip)

**Comment by Utopia1916** [comment]
一样开寻路闪退，我没装MasaGadget，崩溃报告里也看不到和哪个模组冲突了

**Comment by litoj** [comment]
I don't understand anything said here, but I also have pathfinding toggle issues - my grame crashes immediatelly when I try to turn it on.

Version: mc 1.20.1; MiniHUD 0.27.0
log:
```log
java.lang.ArrayIndexOutOfBoundsException: Index 115 out of bounds for length 25
	at net.minecraft.class_2540.method_10818(class_2540.java:518) ~[client-intermediary.jar:?]
	at net.minecraft.class_9.method_47935(class_9.java:155) ~[client-intermediary.jar:?]
	at net.minecraft.class_9.method_28(class_9.java:147) ~[client-intermediary.jar:?]
	at net.minecraft.class_11.method_34(class_11.java:211) ~[client-intermediary.jar:?]
	at fi.dy.masa.minihud.util.DebugInfoUtils.onServerTickEnd(DebugInfoUtils.java:188) ~[minihud-fabric-1.20.1-0.27.0.jar:?]
	at net.minecraft.server.MinecraftServer.handler$ddh000$minihud$onServerTickPost(MinecraftServer.java:5306) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by Utopia1916** [comment]
[minecraft-exported-logs-2024-03-04T13-49-36.log](https://github.com/maruohon/minihud/files/14477048/minecraft-exported-logs-2024-03-04T13-49-36.log)

Here are all the crash logs ，I only loaded two mod: malilib and minihud，but the game still crashes when I turn on pathfinding rendering

**Comment by maruohon** [comment]
I always forget to even test the path finding renderer, and they have changed that code in vanilla a few times recently... so basically that code in MiniHUD isn't updated in some of the recent MC versions.

**Comment by Utopia1916** [comment]
> I always forget to even test the path finding renderer, and they have changed that code in vanilla a few times recently... so basically that code in MiniHUD isn't updated in some of the recent MC versions.

That sounds disheartening. Will there be updates and fixes afterward?

**Comment by maruohon** [comment]
Possibly yes. I at least still want to release the "new code versions" of my mods to all MC versions at some point, so it should get fixed at the latest at that point, but those are still quite far in the future... if they actually ever happen at all.

I think I now remember looking at this when I did the 1.20.2 update where I updated the path finding renderer. And the same patch didn't apply cleanly to the older versions because the vanilla code had changed since then, so then I didn't bother making that fix for the older versions at that point.

**Comment by Utopia1916** [comment]
> Possibly yes. I at least still want to release the "new code versions" of my mods to all MC versions at some point, so it should get fixed at the latest at that point, but those are still quite far in the future... if they actually ever happen at all.
> 
> I think I now remember looking at this when I did the 1.20.2 update where I updated the path finding renderer. And the same patch didn't apply cleanly to the older versions because the vanilla code had changed since then, so then I didn't bother making that fix for the older versions at that point.

Oh, thank you for not abandoning the old version; that is truly commendable. look forward to your updates. 
Additionally, thank you for your contributions to the community. your efforts are greatly appreciated.
