### ISSUE TITLE
Tried to install Litematica, Rift crashes

### ISSUE THREAD

**Issue by githubUser673** [maruohon/minihud#55]
I have Litematica and MaLiLib for 1.13.2 in the mods folder, and Rift keeps crashing with or without them in there. I get this error:
```
[Info: 2020-05-11 15:21:21.4580881: GameCallbacks.cpp(158)] Game/LaunchWrapper (main) Error Unable to launch
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:28)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26)
	... 2 more
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/launch/MixinBootstrap
	at org.dimdev.rift.Rift.onInitialization(Rift.java:23)
	at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:196)
	at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:55)
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinBootstrap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 12 more

[Info: 2020-05-11 15:21:21.4946081: GameCallbacks.cpp(158)] Launcher/launcher (main) Inf
```

Someone more knowledgeable know what is going on?

**Comment by vacla** [comment]
@githubUser673 how did you install rift?

**Comment by githubUser673** [comment]
used the .jar installer on a normal minecraft launcher (if that's specific enough)

**Comment by vacla** [comment]
not really, did you double click the jar, or opened it with java?

**Comment by githubUser673** [comment]
Just doubled clicked the jar file

**Comment by maruohon** [comment]
I don't know if the normal installer for the vanilla launcher works anymore at all, since some of the maven repositories are down.

I recently made a new MultiMC import that embeds all the required libraries, so it doesn't depend on any external servers (except for vanilla stuff). I personally always use MultiMC anyways, and I would highly recommend it for anyone who plays with mods.

The instance import is available here: https://cdn.discordapp.com/attachments/385193086713593858/705439450011926580/mmc_rift_1.13.2_local_libs.zip

And MultiMC itself can be found at: https://multimc.org
