### ISSUE TITLE
Game crashed when turning on bounding boxes.

### ISSUE THREAD

**Issue by geertbruls** [maruohon/minihud#60]
Hey I turned on bounding boxes and my game crashed. I tried removing my other mods and that still wont work. heres the crash report:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 26-5-20 20:04
Description: Unexpected error

java.lang.NoSuchMethodError: fi.dy.masa.malilib.render.RenderUtils.drawBox(Lfi/dy/masa/malilib/util/IntBoundingBox;Lfi/dy/masa/malilib/util/Color4f;Lnet/minecraft/class_287;Lnet/minecraft/class_287;)V
	at fi.dy.masa.minihud.renderer.OverlayRendererStructures.renderStructure(OverlayRendererStructures.java:123)
	at fi.dy.masa.minihud.renderer.OverlayRendererStructures.renderStructuresWithinRange(OverlayRendererStructures.java:113)
	at fi.dy.masa.minihud.renderer.OverlayRendererStructures.updateStructures(OverlayRendererStructures.java:101)
	at fi.dy.masa.minihud.renderer.OverlayRendererStructures.update(OverlayRendererStructures.java:72)
	at fi.dy.masa.minihud.renderer.RenderContainer.update(RenderContainer.java:88)
	at fi.dy.masa.minihud.renderer.RenderContainer.render(RenderContainer.java:70)
	at fi.dy.masa.minihud.renderer.OverlayRenderer.renderOverlays(OverlayRenderer.java:36)
	at fi.dy.masa.minihud.event.RenderHandler.onRenderWorldLast(RenderHandler.java:174)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:99)
	at net.minecraft.class_761.handler$zzk000$onRenderWorldLast(class_761.java:3474)
	at net.minecraft.class_761.method_22710(class_761.java:1326)
	at net.minecraft.class_757.method_3188(class_757.java:718)
	at net.minecraft.class_757.method_3192(class_757.java:543)
	at net.minecraft.class_310.method_1523(class_310.java:989)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.minihud.renderer.OverlayRendererStructures.renderStructure(OverlayRendererStructures.java:123)
	at fi.dy.masa.minihud.renderer.OverlayRendererStructures.renderStructuresWithinRange(OverlayRendererStructures.java:113)
	at fi.dy.masa.minihud.renderer.OverlayRendererStructures.updateStructures(OverlayRendererStructures.java:101)
	at fi.dy.masa.minihud.renderer.OverlayRendererStructures.update(OverlayRendererStructures.java:72)
	at fi.dy.masa.minihud.renderer.RenderContainer.update(RenderContainer.java:88)
	at fi.dy.masa.minihud.renderer.RenderContainer.render(RenderContainer.java:70)
	at fi.dy.masa.minihud.renderer.OverlayRenderer.renderOverlays(OverlayRenderer.java:36)
	at fi.dy.masa.minihud.event.RenderHandler.onRenderWorldLast(RenderHandler.java:174)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:99)
	at net.minecraft.class_761.handler$zzk000$onRenderWorldLast(class_761.java:3474)
	at net.minecraft.class_761.method_22710(class_761.java:1326)
	at net.minecraft.class_757.method_3188(class_757.java:718)

-- Affected level --
Details:
	All players: 1 total; [class_746['kinggeert'/27, l='MpServer', x=-215.14, y=64.92, z=37.84]]
	Chunk stats: Client Chunk Cache: 1849, 766
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 3202862393163040595
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-265,67,39), Chunk: (at 7,4,7 in -17,2; contains blocks -272,0,32 to -257,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3507600 game time, 6000 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1209631144 bytes (1153 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.7.8+build.184-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaTweaks_r381731.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor

**Comment by vacla** [comment]
@kinggeert you need to update malilib and/or minihud https://masa.dy.fi/tmp/minecraft/mods/client_mods/
