### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by iPollox** [maruohon/minihud#8]
Before posting, I tried a different Rift mod, and launched and worked.
This is for 1.13.2, I already tried a fresh install using the Vanilla Launcher, and yield the same error as MultiMC.

> [21:59:25] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:28) ~[rift-jitpack-d6893ec777-1.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[rift-jitpack-d6893ec777-1.jar:?]
	... 10 more
Caused by: java.lang.NoClassDefFoundError: fi/dy/masa/malilib/interfaces/IInitializationHandler
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:254) ~[rift-jitpack-d6893ec777-1.jar:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:239) ~[rift-jitpack-d6893ec777-1.jar:?]
	at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:194) ~[rift-jitpack-d6893ec777-1.jar:?]
	at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:55) ~[rift-jitpack-d6893ec777-1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[rift-jitpack-d6893ec777-1.jar:?]
	... 10 more
Caused by: java.lang.ClassNotFoundException: fi.dy.masa.malilib.interfaces.IInitializationHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:254) ~[rift-jitpack-d6893ec777-1.jar:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:239) ~[rift-jitpack-d6893ec777-1.jar:?]
	at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:194) ~[rift-jitpack-d6893ec777-1.jar:?]
	at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:55) ~[rift-jitpack-d6893ec777-1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[rift-jitpack-d6893ec777-1.jar:?]
	... 10 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:254) ~[rift-jitpack-d6893ec777-1.jar:?]
	at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:239) ~[rift-jitpack-d6893ec777-1.jar:?]
	at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:194) ~[rift-jitpack-d6893ec777-1.jar:?]
	at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:55) ~[rift-jitpack-d6893ec777-1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[rift-jitpack-d6893ec777-1.jar:?]
	... 10 more

**Comment by skyrising** [comment]
You also need malilib to tun MiniHUD

**Comment by iPollox** [comment]
Oh gotcha, when I clicked Download Latest File, it downloads an older version and its a liteloader mod, had to manually go into the files tab, thank you so much
