### ISSUE TITLE
Game crashes when loading world

### ISSUE THREAD

**Issue by Morgz13** [maruohon/minihud#83]
Minecraft 1.16.2 boots up as normal but every time I attempt to enter or create a new single player world, or join a server, the game crashes. I tried updating to latest fabric & api and still have it crash.

Error with 0.17.2 Fabric API

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 22/08/20 4:04 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraft/class_5318
	at fi.dy.masa.malilib.util.WorldUtils.getDimensionId(WorldUtils.java:16)
	at fi.dy.masa.malilib.util.StringUtils.getStorageFileName(StringUtils.java:341)
	at fi.dy.masa.minihud.event.WorldLoadListener.getCurrentStorageFile(WorldLoadListener.java:159)
	at fi.dy.masa.minihud.event.WorldLoadListener.readStoredDataPerDimension(WorldLoadListener.java:109)
	at fi.dy.masa.minihud.event.WorldLoadListener.onWorldLoadPost(WorldLoadListener.java:72)
	at fi.dy.masa.malilib.event.WorldLoadHandler.onWorldLoadPost(WorldLoadHandler.java:88)
	at net.minecraft.class_634.handler$zcm000$onPostGameJoin(class_634.java:3950)
	at net.minecraft.class_634.method_11120(class_634.java:411)
	at net.minecraft.class_2678.method_11567(class_2678.java:110)
	at net.minecraft.class_2678.method_11054(class_2678.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.class_310.method_1523(class_310.java:990)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5318
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 33 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.malilib.util.WorldUtils.getDimensionId(WorldUtils.java:16)
	at fi.dy.masa.malilib.util.StringUtils.getStorageFileName(StringUtils.java:341)
	at fi.dy.masa.minihud.event.WorldLoadListener.getCurrentStorageFile(WorldLoadListener.java:159)
	at fi.dy.masa.minihud.event.WorldLoadListener.readStoredDataPerDimension(WorldLoadListener.java:109)
	at fi.dy.masa.minihud.event.WorldLoadListener.onWorldLoadPost(WorldLoadListener.java:72)
	at fi.dy.masa.malilib.event.WorldLoadHandler.onWorldLoadPost(WorldLoadHandler.java:88)
	at net.minecraft.class_634.handler$zcm000$onPostGameJoin(class_634.java:3950)
	at net.minecraft.class_634.method_11120(class_634.java:411)
	at net.minecraft.class_2678.method_11567(class_2678.java:110)
	at net.minecraft.class_2678.method_11054(class_2678.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118) 

Error with 0.19.0 Fabric API 

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 22/08/20 4:06 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraft/class_5318
	at fi.dy.masa.malilib.util.WorldUtils.getDimensionId(WorldUtils.java:16)
	at fi.dy.masa.malilib.util.StringUtils.getStorageFileName(StringUtils.java:341)
	at fi.dy.masa.minihud.event.WorldLoadListener.getCurrentStorageFile(WorldLoadListener.java:159)
	at fi.dy.masa.minihud.event.WorldLoadListener.readStoredDataPerDimension(WorldLoadListener.java:109)
	at fi.dy.masa.minihud.event.WorldLoadListener.onWorldLoadPost(WorldLoadListener.java:72)
	at fi.dy.masa.malilib.event.WorldLoadHandler.onWorldLoadPost(WorldLoadHandler.java:88)
	at net.minecraft.class_634.handler$zda000$onPostGameJoin(class_634.java:3950)
	at net.minecraft.class_634.method_11120(class_634.java:411)
	at net.minecraft.class_2678.method_11567(class_2678.java:110)
	at net.minecraft.class_2678.method_11054(class_2678.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.class_310.method_1523(class_310.java:990)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5318
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 33 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.malilib.util.WorldUtils.getDimensionId(WorldUtils.java:16)
	at fi.dy.masa.malilib.util.StringUtils.getStorageFileName(StringUtils.java:341)
	at fi.dy.masa.minihud.event.WorldLoadListener.getCurrentStorageFile(WorldLoadListener.java:159)
	at fi.dy.masa.minihud.event.WorldLoadListener.readStoredDataPerDimension(WorldLoadListener.java:109)
	at fi.dy.masa.minihud.event.WorldLoadListener.onWorldLoadPost(WorldLoadListener.java:72)
	at fi.dy.masa.malilib.event.WorldLoadHandler.onWorldLoadPost(WorldLoadHandler.java:88)
	at net.minecraft.class_634.handler$zda000$onPostGameJoin(class_634.java:3950)
	at net.minecraft.class_634.method_11120(class_634.java:411)
	at net.minecraft.class_2678.method_11567(class_2678.java:110)
	at net.minecraft.class_2678.method_11054(class_2678.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)

**Comment by vacla** [comment]
You need to update malilib

**Comment by Morgz13** [comment]
> You need to update malilib

I have the latest malilib that I can see? I got it off https://www.curseforge.com/minecraft/mc-mods/malilib/files 

https://masa.dy.fi/mcmods/client_mods/   also shows the same.

Where would I find a more recent version?

**Comment by vacla** [comment]
When i checked the logs, you had 1.16.1 malilib and not 1.16.2 malilib
Both has latest version

**Comment by Morgz13** [comment]
> When i checked the logs, you had 1.16.1 malilib and not 1.16.2 malilib
> Both has latest version

I redownloaded and installed, it didnt work. So I deleted every single past instance of malilib and downloaded it again, it works! Idky but thank you.
